In [1]:
import torch
from sklearn.datasets import make_classification

In [2]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [4]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
        
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [5]:
dataset = CustomDataset(X,y)

In [6]:
len(dataset)

10

In [7]:
dataset[3]

(array([-0.72063436, -0.96059253]), np.int64(0))

In [8]:
dataset[[2,6]]

(array([[-2.8953973 ,  1.97686236],
        [ 1.72725924, -1.18582677]]),
 array([0, 1]))

In [9]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [10]:
for batch_feattures, batch_labels in dataloader:
    print(batch_feattures)
    print(batch_labels)
    print("--------------")

tensor([[-2.8954,  1.9769],
        [-1.9629, -0.9923]], dtype=torch.float64)
tensor([0, 0])
--------------
tensor([[-0.7206, -0.9606],
        [ 1.0683, -0.9701]], dtype=torch.float64)
tensor([0, 1])
--------------
tensor([[ 1.7774,  1.5116],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([1, 1])
--------------
tensor([[-1.1402, -0.8388],
        [-0.9382, -0.5430]], dtype=torch.float64)
tensor([0, 1])
--------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([1, 0])
--------------
