In [1]:
import torch
print(torch.__version__)

2.11.0+cu126


# 1. Creating Tensor

In [2]:
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [3]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [5]:
torch.rand(2,3)

tensor([[0.7503, 0.8105, 0.5219],
        [0.8430, 0.7732, 0.7335]])

In [6]:
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [7]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [8]:
torch.linspace(0,10,6)

tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
torch.full((3,2), 5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [11]:
torch.randint(size=(2,3), low=0,high=10)

tensor([[3, 8, 3],
        [8, 0, 2]])

# 2. Tensor Shape

In [12]:
X = torch.tensor([[1,2,3], [4,5,6]])
X.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(X, dtype=torch.float32)

tensor([[0.7822, 0.1743, 0.4810],
        [0.3342, 0.7257, 0.9444]])

# 3. Tensor Datatype

In [17]:
X.dtype

torch.int64

In [18]:
torch.tensor(X, dtype=torch.float32)

C:\Users\Jehan\AppData\Local\Temp\ipykernel_4748\2588671146.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(X, dtype=torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
X.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

# 4. Mathematical Operation
### i) Scaler

In [20]:
x = torch.tensor([[.1,.2,.3],[.4,.5,.6]])

In [21]:
x + 2

tensor([[2.1000, 2.2000, 2.3000],
        [2.4000, 2.5000, 2.6000]])

In [22]:
x - 2 

tensor([[-1.9000, -1.8000, -1.7000],
        [-1.6000, -1.5000, -1.4000]])

In [23]:
x * 3

tensor([[0.3000, 0.6000, 0.9000],
        [1.2000, 1.5000, 1.8000]])

In [24]:
x / 3

tensor([[0.0333, 0.0667, 0.1000],
        [0.1333, 0.1667, 0.2000]])

In [25]:
x // 3

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
x ** 2

tensor([[0.0100, 0.0400, 0.0900],
        [0.1600, 0.2500, 0.3600]])

In [27]:
x % 2

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

### ii) Element wise

In [28]:
x = torch.randint(size=(2,3), low=1, high=10)
y = torch.randint(size=(2,3), low=1, high=10)
print(x,"\n", y)

tensor([[3, 5, 6],
        [9, 6, 6]]) 
 tensor([[4, 3, 3],
        [6, 5, 2]])


In [29]:
x + y 

tensor([[ 7,  8,  9],
        [15, 11,  8]])

In [30]:
x - y

tensor([[-1,  2,  3],
        [ 3,  1,  4]])

In [31]:
x / y 

tensor([[0.7500, 1.6667, 2.0000],
        [1.5000, 1.2000, 3.0000]])

In [32]:
x // y 

tensor([[0, 1, 2],
        [1, 1, 3]])

### iii) Function

In [33]:
x = torch.linspace(-1,1,5) * 10
x

tensor([-10.,  -5.,   0.,   5.,  10.])

In [34]:
torch.abs(x)

tensor([10.,  5.,  0.,  5., 10.])

In [35]:
torch.neg(x)

tensor([ 10.,   5.,  -0.,  -5., -10.])

In [36]:
x = torch.rand((2,3)) * 10
x

tensor([[4.7901, 4.3373, 7.1893],
        [5.5634, 1.7117, 9.9308]])

In [37]:
torch.round(x)

tensor([[ 5.,  4.,  7.],
        [ 6.,  2., 10.]])

In [38]:
torch.ceil(x)

tensor([[ 5.,  5.,  8.],
        [ 6.,  2., 10.]])

In [39]:
torch.floor(x)

tensor([[4., 4., 7.],
        [5., 1., 9.]])

In [40]:
torch.clamp(x, min=2, max=6)

tensor([[4.7901, 4.3373, 6.0000],
        [5.5634, 2.0000, 6.0000]])

# iv) Statistical Operation
#### (Col wise--> 0) (Row wise --> 1)

In [41]:
x

tensor([[4.7901, 4.3373, 7.1893],
        [5.5634, 1.7117, 9.9308]])

In [42]:
print(torch.sum(x))
print("------------")
print(torch.sum(x, dim=0))    # col wise
print("------------")
print(torch.sum(x, dim=1))    # row wise

tensor(33.5227)
------------
tensor([10.3535,  6.0491, 17.1200])
------------
tensor([16.3167, 17.2060])


In [43]:
print(torch.mean(x))
print("------------")
print(torch.mean(x, dim=0))    # col wise
print("------------")
print(torch.mean(x, dim=1))    # row wise

tensor(5.5871)
------------
tensor([5.1768, 3.0245, 8.5600])
------------
tensor([5.4389, 5.7353])


In [44]:
print(torch.min(x))
print("------------")
print(torch.min(x, dim=0))    # col wise
print("------------")
print(torch.min(x, dim=1))    # row wise

tensor(1.7117)
------------
torch.return_types.min(
values=tensor([4.7901, 1.7117, 7.1893]),
indices=tensor([0, 1, 0]))
------------
torch.return_types.min(
values=tensor([4.3373, 1.7117]),
indices=tensor([1, 1]))


In [45]:
print(torch.max(x))
print("------------")
print(torch.max(x, dim=0))    # col wise
print("------------")
print(torch.max(x, dim=1))    # row wise

tensor(9.9308)
------------
torch.return_types.max(
values=tensor([5.5634, 4.3373, 9.9308]),
indices=tensor([1, 0, 1]))
------------
torch.return_types.max(
values=tensor([7.1893, 9.9308]),
indices=tensor([2, 2]))


In [46]:
print(torch.var(x))
print("------------")
print(torch.var(x, dim=0))    # col wise
print("------------")
print(torch.var(x, dim=1))    # row wise

tensor(7.7301)
------------
tensor([0.2990, 3.4469, 3.7579])
------------
tensor([ 2.3491, 16.9103])


In [47]:
print(torch.argmin(x))
print("------------")
print(torch.argmin(x, dim=0))    # col wise
print("------------")
print(torch.argmin(x, dim=1))    # row wise

tensor(4)
------------
tensor([0, 1, 0])
------------
tensor([1, 1])


In [48]:
print(torch.argmax(x))
print("------------")
print(torch.argmax(x, dim=0))    # col wise
print("------------")
print(torch.argmax(x, dim=1))    # row wise

tensor(5)
------------
tensor([1, 0, 1])
------------
tensor([2, 2])


# 5. Matrix Operation

In [49]:
x = torch.rand(2,3)
y = torch.rand(3,4)
print(x,"\n",y)

tensor([[0.3752, 0.3902, 0.7989],
        [0.8348, 0.9205, 0.3513]]) 
 tensor([[0.1676, 0.8515, 0.0294, 0.5071],
        [0.6282, 0.2440, 0.1146, 0.2711],
        [0.2621, 0.4622, 0.6484, 0.8526]])


In [50]:
torch.matmul(x,y)

tensor([[0.5174, 0.7839, 0.5738, 0.9772],
        [0.8103, 1.0978, 0.3578, 0.9724]])

In [51]:
a = torch.rand(3)
b = torch.rand(3)
print(a,"\n",b)

tensor([0.8788, 0.3444, 0.8551]) 
 tensor([0.9446, 0.5319, 0.6192])


In [52]:
torch.dot(a,b)

tensor(1.5428)

In [53]:
x.T

tensor([[0.3752, 0.8348],
        [0.3902, 0.9205],
        [0.7989, 0.3513]])

In [54]:
p = torch.rand(3,3)
p

tensor([[0.6782, 0.5134, 0.9996],
        [0.7322, 0.9777, 0.2156],
        [0.6340, 0.9492, 0.4336]])

In [55]:
torch.det(p)

tensor(0.1311)

In [56]:
torch.inverse(p)

tensor([[ 1.6724,  5.5407, -6.6113],
        [-1.3792, -2.5915,  4.4686],
        [ 0.5741, -2.4281,  2.1903]])

# 6. Boolean Operation

In [57]:
x = torch.rand(2,3) * 100
y = torch.rand(2,3) * 100
print(x,"\n",y)

tensor([[20.7012, 88.5334,  8.4349],
        [99.9544, 16.2897, 78.4344]]) 
 tensor([[72.6404, 31.9411, 31.3621],
        [20.9071, 99.3328, 12.1223]])


In [58]:
x > y

tensor([[False,  True, False],
        [ True, False,  True]])

In [59]:
x[x > y]

tensor([88.5334, 99.9544, 78.4344])

In [60]:
x[x < y]

tensor([20.7012,  8.4349, 16.2897])

In [61]:
x == y

tensor([[False, False, False],
        [False, False, False]])

In [62]:
x != y

tensor([[True, True, True],
        [True, True, True]])

# 7. Special Function

In [63]:
x = torch.rand(2,3)
x

tensor([[0.7643, 0.0505, 0.2088],
        [0.0896, 0.4799, 0.4814]])

In [64]:
torch.log(x)

tensor([[-0.2688, -2.9862, -1.5664],
        [-2.4129, -0.7342, -0.7310]])

In [65]:
torch.exp(x)

tensor([[2.1475, 1.0518, 1.2322],
        [1.0937, 1.6159, 1.6184]])

In [66]:
torch.sigmoid(x)

tensor([[0.6823, 0.5126, 0.5520],
        [0.5224, 0.6177, 0.6181]])

In [67]:
torch.softmax(x, dim=0)   # col wise

tensor([[0.6626, 0.3943, 0.4323],
        [0.3374, 0.6057, 0.5677]])

In [68]:
torch.softmax(x, dim=1)   # row wise

tensor([[0.4846, 0.2373, 0.2781],
        [0.2527, 0.3734, 0.3739]])

In [69]:
torch.relu(x)

tensor([[0.7643, 0.0505, 0.2088],
        [0.0896, 0.4799, 0.4814]])

# 8. Inplace Operation

In [70]:
x = torch.rand(2,3) 
y = torch.rand(2,3)
print(x,"\n",y)

tensor([[0.2537, 0.3756, 0.6020],
        [0.0361, 0.5205, 0.2404]]) 
 tensor([[0.3226, 0.8751, 0.7656],
        [0.4020, 0.4435, 0.3185]])


In [71]:
x.add(y)

tensor([[0.5763, 1.2506, 1.3676],
        [0.4381, 0.9640, 0.5589]])

In [72]:
x

tensor([[0.2537, 0.3756, 0.6020],
        [0.0361, 0.5205, 0.2404]])

In [73]:
x.add_(y)
x

tensor([[0.5763, 1.2506, 1.3676],
        [0.4381, 0.9640, 0.5589]])

In [74]:
x.relu_()

tensor([[0.5763, 1.2506, 1.3676],
        [0.4381, 0.9640, 0.5589]])

# 9. Copy Tensor

In [75]:
c = x.clone()
c

tensor([[0.5763, 1.2506, 1.3676],
        [0.4381, 0.9640, 0.5589]])

# 10. GPU operation

In [76]:
torch.cuda.is_available()

True

In [77]:
device = torch.device("cuda")
device

device(type='cuda')

In [78]:
torch.rand((2,3), device=device)

tensor([[0.1160, 0.2757, 0.5699],
        [0.5466, 0.5732, 0.8244]], device='cuda:0')

# 11. Numpy -> Pytoch

In [79]:
import numpy as np 

In [83]:
# numpy -> torch
np_arr = np.random.rand(2,3)
torch.from_numpy(np_arr)

tensor([[0.7197, 0.2089, 0.2767],
        [0.2475, 0.2782, 0.2160]], dtype=torch.float64)

In [82]:
# torch -> numpy
x_torch = torch.rand(2,3)
x_torch.numpy()

array([[0.6539845 , 0.19882274, 0.04734462],
       [0.62854713, 0.983809  , 0.9441119 ]], dtype=float32)