In [1]:
import torch

# y = x <sup>2</sup>

In [2]:
x = torch.tensor(3.0, requires_grad=True)
x

tensor(3., requires_grad=True)

In [3]:
# y = x^2
# dy/dx for value of x=3
# dy/dx = 2x = 2*3 = 6

y = x ** 2
y

tensor(9., grad_fn=<PowBackward0>)

In [4]:
y.backward()

In [5]:
x.grad

tensor(6.)

# y = x <sup>2</sup>
# z = sin(y)

In [6]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
z = torch.sin(y)

z.backward()
x.grad

tensor(-2.6146)

# y = x<sup>2</sup>
# z = sin(y)
# u = e <sup> z </sup>

In [7]:
x = torch.tensor(5.47, requires_grad=True)
y = x ** 2
z = torch.sin(y)
u = torch.exp(z)

u.backward()
x.grad

tensor(0.3055)

# Multivariate Function (partial Derivative)

y = (x<sub>1</sub><sup>2</sup> + x<sub>2</sub><sup>2</sup> + x<sub>3</sub><sup>2</sup> ) / 3

In [8]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = (x**2).mean()

y.backward()
x.grad

tensor([0.6667, 1.3333, 2.0000])

# Perceptron Backpropagation

In [9]:
x = torch.tensor(6.7)
y_true = torch.tensor(0.0)

In [10]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [11]:
print(x.shape)
print(x.unsqueeze(dim=0).shape)

torch.Size([])
torch.Size([1])


In [12]:
z = torch.dot( x.unsqueeze(0) , w.unsqueeze(0) ) + b.unsqueeze(0)
y_pred = torch.sigmoid(z)
y_pred

tensor([0.9988], grad_fn=<SigmoidBackward0>)

In [13]:
def binary_cross_entropy(y_true, y_pred):
    ephcilon = 1e-8
    y_pred = torch.clamp(y_pred,ephcilon, 1-ephcilon)
    return -(y_true * torch.log(y_pred) + (1-y_true)*torch.log(1-y_pred))

In [14]:
binary_cross_entropy(torch.tensor(1.0), torch.tensor(0.68))

tensor(0.3857)

In [15]:
loss = binary_cross_entropy(y_true, y_pred)
loss

tensor([6.7012], grad_fn=<NegBackward0>)

In [16]:
loss.backward()
print(w.grad, b.grad)

tensor(6.6918) tensor(0.9988)


# Multi Layer Perceptron

In [17]:
X = torch.tensor([3.9,8.9 ,90])
y_true = torch.tensor(0.0)

In [18]:
W1 = torch.rand(3,3, requires_grad=True)    
B1 = torch.rand(3, requires_grad=True)
print(W1,"\n",B1)

tensor([[0.4542, 0.3851, 0.7819],
        [0.2548, 0.8061, 0.4764],
        [0.5719, 0.2653, 0.4021]], requires_grad=True) 
 tensor([0.8783, 0.7846, 0.9809], requires_grad=True)


In [19]:
# X(1,3) * W1(3,3) = (1,3) + B1(1,3)  = z1(1,3)
z1 = torch.matmul(X, W1) + B1
z1

tensor([56.3854, 33.3404, 44.4572], grad_fn=<AddBackward0>)

In [20]:
o1 = torch.relu(z1)
o1

tensor([56.3854, 33.3404, 44.4572], grad_fn=<ReluBackward0>)

In [25]:
# X(1,3) * W2(3,3) = (1,3) + B2(1,3)  = z2(1,3)
W2 = torch.rand(3,3, requires_grad=True)    
B2 = torch.rand(3, requires_grad=True)
z2 = torch.matmul(o1, W2) + B2
o2 = torch.sigmoid(z2)

In [26]:
loss = binary_cross_entropy(y_true, o2)
loss

tensor([inf, inf, inf], grad_fn=<NegBackward0>)

In [27]:
loss.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [28]:
W1.grad