In [1]:
import torch

# your journey starts with one step
inputs = torch.tensor([
    [0.43, 0.15, 0.89], # Your     (x^1)
    [0.55, 0.87, 0.66], # journey  (x^2)
    [0.57, 0.85, 0.64], # starts   (x^3)
    [0.22, 0.58, 0.33], # with     (x^4)
    [0.77, 0.25, 0.10], # one      (x^5)
    [0.05, 0.80, 0.55]  # step     (x^6)
] )

# For 2nd row [journey]

In [2]:
query_2  = inputs[1]  
query_2

tensor([0.5500, 0.8700, 0.6600])

In [3]:
attention_score_2 = torch.empty(inputs.shape[0])   # size = 6
attention_score_2

tensor([-1.6932e-24,  1.2135e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00])

In [4]:
for index, row_of_input in enumerate(inputs):
    attention_score_2[index] = torch.dot(row_of_input, query_2)
    
attention_score_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [10]:
# Normalize 
attention_weight_2 = torch.softmax(attention_score_2, dim=-1)   # based on row 
attention_weight_2

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

# For all row

In [9]:
attention_score = torch.empty(inputs.shape[0], inputs.shape[0])  # (6 * 6)
for i, row_of_input in enumerate(inputs):
    for j, row_as_query in enumerate(inputs):
        attention_score[i][j] = torch.dot(row_of_input, row_as_query)
    
attention_score

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [11]:
attention_weight = torch.softmax(attention_score, dim=-1)   # based on col (sum of row = 0)
attention_weight

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [14]:
print(torch.sum(attention_weight, dim=0))  # ❌
print(torch.sum(attention_weight, dim=-1))  # ✅  # based on col (sum of row = 0)

tensor([0.9220, 1.2970, 1.2788, 0.7974, 0.7540, 0.9508])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


# Using Matrix Multiplication

In [15]:
attention_score = inputs @ inputs.T
attention_score

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])

In [16]:
attention_weight = torch.softmax(attention_score, dim=-1)   # based on col (sum of row = 0)
attention_weight

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])

In [ ]:
context_vector = attention_weight @ inputs   # (6,6) * (6,3) -> (6,3)
context_vector