In [1]:
import pandas as pd

df = pd.read_csv("../../../Data/Question-Answer.csv").sample(500)
df.drop(columns=['distractor'],inplace=True)
df

,question,answer_text
20799,Why did Sue come up to the instructor 's family ?,To have a chat with the couple .
15226,What 's the main idea of the passage ?,An endangered language is spoken by only two p...
12458,What 's the best title for the text ?,Lunches packed with love .
22099,The best title of the passage is,Passing help
27284,What would be the best title for the text ?,An Unusual Architect -- Ieoh Ming Pei
...,...,...
30757,What did Rohm do when she saw the two boys ?,She asked them to ask their parents for help .
11029,We can learn from the passage that,the girl has played ping - pong many times
27722,Hybrid cars consume less energy than conventio...,have electric power to assist when needed
22967,The title of the passage should be,Short stature and short life


# 1. Tokenization

In [2]:
def clean_sentence(text):
    return (
        text
        .replace("?","")
        .replace("!","")
        .replace("'","")
        .replace(",","")
        .replace(".","")
        .replace(":","")
        .replace("(","")
        .replace(")","")
    )

In [3]:
clean_sentence("What can we learn about Friends")

'What can we learn about Friends'

In [4]:
document = []
def text_document(row):
    question = clean_sentence(row['question'])
    answer = clean_sentence(row['answer_text'])
    
    merge_tokens = question + answer
    
    document.append(merge_tokens)

In [5]:
df.apply(text_document, axis=1)
document

['Why did Sue come up to the instructor s family To have a chat with the couple ',
 'What s the main idea of the passage An endangered language is spoken by only two people ',
 'What s the best title for the text Lunches packed with love ',
 'The best title   of the passage isPassing help',
 'What would be the best title for the text An Unusual Architect -- Ieoh Ming Pei',
 'What do we know about Reading Recovery Children on the project showed noticeable progress in reading ',
 'What does Helen do when she is with Betty Talk about her baby sister',
 'The writer probably agrees thatyou should consider others  response before you act assertively',
 'The passage is mainly aboutthe effects of the nuclear radiation leaks',
 'What s the best title for the text Grandpa s Birdhouses',
 'What s Whitney Houston s most outstanding achievements Her record - setting string of seven Number One singles ',
 'What s the name of the new picture book that recaptures the capital s Lunar New Year tradition

# 2. Build vocab

In [6]:
vocab = {
    "UNK":0
}

In [7]:
from nltk.tokenize import word_tokenize
for sentence in document:
    tokenized_word = word_tokenize(sentence)
    for token in tokenized_word:
        if token not in vocab:
            vocab[token] = len(vocab)

In [8]:
print(len(vocab))
vocab

2420


{'UNK': 0,
 'Why': 1,
 'did': 2,
 'Sue': 3,
 'come': 4,
 'up': 5,
 'to': 6,
 'the': 7,
 'instructor': 8,
 's': 9,
 'family': 10,
 'To': 11,
 'have': 12,
 'a': 13,
 'chat': 14,
 'with': 15,
 'couple': 16,
 'What': 17,
 'main': 18,
 'idea': 19,
 'of': 20,
 'passage': 21,
 'An': 22,
 'endangered': 23,
 'language': 24,
 'is': 25,
 'spoken': 26,
 'by': 27,
 'only': 28,
 'two': 29,
 'people': 30,
 'best': 31,
 'title': 32,
 'for': 33,
 'text': 34,
 'Lunches': 35,
 'packed': 36,
 'love': 37,
 'The': 38,
 'isPassing': 39,
 'help': 40,
 'would': 41,
 'be': 42,
 'Unusual': 43,
 'Architect': 44,
 '--': 45,
 'Ieoh': 46,
 'Ming': 47,
 'Pei': 48,
 'do': 49,
 'we': 50,
 'know': 51,
 'about': 52,
 'Reading': 53,
 'Recovery': 54,
 'Children': 55,
 'on': 56,
 'project': 57,
 'showed': 58,
 'noticeable': 59,
 'progress': 60,
 'in': 61,
 'reading': 62,
 'does': 63,
 'Helen': 64,
 'when': 65,
 'she': 66,
 'Betty': 67,
 'Talk': 68,
 'her': 69,
 'baby': 70,
 'sister': 71,
 'writer': 72,
 'probably': 73,
 'ag

# 3. Text to numeric representation

In [9]:
def line_to_numeric_rep(sentence, vocab):
    numerical_present = []
    for word in word_tokenize(sentence):
        if word in vocab:
            numerical_present.append(vocab[word])
        else:
            numerical_present.append(0)
    return numerical_present

In [10]:
line_to_numeric_rep("What can we learn about Friends",vocab)

[17, 144, 50, 216, 52, 807]

In [11]:
numerical_document = []
for sentence in document:
    numerical_document.append(line_to_numeric_rep(sentence,vocab))

numerical_document

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 16],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
 [17, 9, 7, 31, 32, 33, 7, 34, 35, 36, 15, 37],
 [38, 31, 32, 20, 7, 21, 39, 40],
 [17, 41, 42, 7, 31, 32, 33, 7, 34, 22, 43, 44, 45, 46, 47, 48],
 [17, 49, 50, 51, 52, 53, 54, 55, 56, 7, 57, 58, 59, 60, 61, 62],
 [17, 63, 64, 49, 65, 66, 25, 15, 67, 68, 52, 69, 70, 71],
 [38, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
 [38, 21, 25, 84, 85, 86, 20, 7, 87, 88, 89],
 [17, 9, 7, 31, 32, 33, 7, 34, 90, 9, 91],
 [17, 9, 92, 93, 9, 94, 95, 96, 97, 98, 99, 100, 101, 20, 102, 103, 104, 105],
 [17,
  9,
  7,
  106,
  20,
  7,
  107,
  108,
  109,
  110,
  111,
  7,
  112,
  9,
  113,
  114,
  115,
  116,
  33,
  117,
  118,
  119,
  61,
  120],
 [1, 121, 122, 123, 124, 125, 126, 127, 126, 123, 128, 129, 130, 131, 20, 132],
 [17,
  9,
  7,
  133,
  20,
  7,
  134,
  110,
  135,
  136,
  137,
  27,
  138,
  139,
  69,
  140,
  11,
  134,
  141,
  142,
  143,
  144

# 4. Next Word Prediction Format

In [12]:
next_word_prediction_data = []

for numerical_sentence in numerical_document:
    for i in range(1, len(numerical_sentence)):
        next_word_prediction_data.append(numerical_sentence[:i+1])

next_word_prediction_data

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5, 6],
 [1, 2, 3, 4, 5, 6, 7],
 [1, 2, 3, 4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5, 6, 7, 8, 9],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7],
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 7, 16],
 [17, 9],
 [17, 9, 7],
 [17, 9, 7, 18],
 [17, 9, 7, 18, 19],
 [17, 9, 7, 18, 19, 20],
 [17, 9, 7, 18, 19, 20, 7],
 [17, 9, 7, 18, 19, 20, 7, 21],
 [17, 9, 7, 18, 19, 20, 7, 21, 22],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 24, 25, 26, 27],
 [17, 9, 7, 18, 19, 20, 7, 21, 22, 23, 2

# 5. Left Padding

In [13]:
maxi = 0
for seq in next_word_prediction_data:
    maxi = max(maxi, len(seq))
    
maxi

47

In [14]:
next_word_prediction_data_padded = []
for sequence in next_word_prediction_data:
    next_word_prediction_data_padded.append([0]*(maxi - len(sequence)) + sequence)
    
next_word_prediction_data_padded

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
 

# 4. Dataloader

In [15]:
import torch

data_tensor = torch.tensor(next_word_prediction_data_padded, dtype=torch.long)
data_tensor

tensor([[   0,    0,    0,  ...,    0,    1,    2],
        [   0,    0,    0,  ...,    1,    2,    3],
        [   0,    0,    0,  ...,    2,    3,    4],
        ...,
        [   0,    0,    0,  ..., 2416,  891, 2417],
        [   0,    0,    0,  ...,  891, 2417, 2418],
        [   0,    0,    0,  ..., 2417, 2418, 2419]])

In [16]:
X = data_tensor[:, :-1]
y = data_tensor[:, -1]

In [17]:
from torch.utils.data import Dataset, DataLoader
import torch

class CustomDataset(Dataset):
    def __init__(self, X,y):
        self.X = X
        self.y = y
        
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, index):
        return self.X[index], self.y[index]

In [18]:
dataset = CustomDataset(X,y)

dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [19]:
for ques, ans in dataloader:
    print(ques)
    print(ans)
    break

tensor([[   0,    0,    0,  ...,  311,    6,    7],
        [   0,    0,    0,  ...,   51,   52,    7],
        [   0,    0,    0,  ...,  319,    6,  320],
        ...,
        [   0,    0,    0,  ..., 2296,  378,   20],
        [   0,    0,    0,  ...,   13,  837,    9],
        [   0,    0,    0,  ...,   17,  193,   76]])
tensor([  21,  185,    6,    6,  315, 2351,   25, 2304,  144,   32,    7,  139,
         475, 1207, 1267,  216, 1358,  126,    2,   25,   42,  532, 2355, 2233,
         433, 1108,  566,  395,  141,    7,  838, 1073])


# 5. Model Build

In [20]:
import torch.nn as nn
class QuesAnsRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim=50)
        self.rnn = nn.RNN(50,64, batch_first=True)
        self.fc = nn.Linear(64, vocab_size)
        
    def forward(self, question):
        embedding_ques = self.embedding(question)
        hidden_output, final_output = self.rnn(embedding_ques)
        return self.fc(final_output.squeeze(0))

# 6. Train Model

In [21]:
learning_rate = 0.001
epochs = 50

In [22]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [23]:
model = QuesAnsRNN(len(vocab)).to(device)

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [24]:
for epoch in range(epochs):
    epochs_loss = 0
    for batch_question, batch_answer in dataloader:
        batch_question, batch_answer = batch_question.to(device), batch_answer.to(device)
        optimizer.zero_grad()
        
        y_pred = model(batch_question)
        
        loss = criterion(y_pred, batch_answer)
        
        loss.backward()
        
        optimizer.step()
        
        epochs_loss += loss.item()
        
    avg_epoch_loss = epochs_loss / len(dataloader)
    print(f"Epoch {epoch+1}: Loss {avg_epoch_loss}")

Epoch 1: Loss 6.827760118666526
Epoch 2: Loss 5.968869533776248
Epoch 3: Loss 5.5779963528961565
Epoch 4: Loss 5.224491659536401
Epoch 5: Loss 4.893950087400888
Epoch 6: Loss 4.580511531394547
Epoch 7: Loss 4.287136377635338
Epoch 8: Loss 4.001420594844581
Epoch 9: Loss 3.733442383683074
Epoch 10: Loss 3.4766373030872266
Epoch 11: Loss 3.2357799462757666
Epoch 12: Loss 3.006864524975852
Epoch 13: Loss 2.7936435378933346
Epoch 14: Loss 2.5924049363591366
Epoch 15: Loss 2.412029300982527
Epoch 16: Loss 2.2468559291847514
Epoch 17: Loss 2.0952442874552304
Epoch 18: Loss 1.9573704113109478
Epoch 19: Loss 1.828470861268736
Epoch 20: Loss 1.7140579836991812
Epoch 21: Loss 1.6083396979882014
Epoch 22: Loss 1.5088552582808055
Epoch 23: Loss 1.4184919751531355
Epoch 24: Loss 1.3323087600751538
Epoch 25: Loss 1.254282747314184
Epoch 26: Loss 1.1832428661124834
Epoch 27: Loss 1.1149582120887471
Epoch 28: Loss 1.0523181490878346
Epoch 29: Loss 0.9950991817035121
Epoch 30: Loss 0.9417755607500116
E

# 7. Inference

In [25]:
def predict(question, threshold=0.5, words=1):
    # tokenize 
    tokens = word_tokenize(question.lower())
    
    # convert text to number
    numerical_question = line_to_numeric_rep(question, vocab)
    
    # padding
    numerical_question_padded = [0]*(maxi - len(numerical_question)) + numerical_question
    
    # make it tensor (push into gpu)
    tensor_question = torch.tensor(numerical_question_padded, dtype=torch.long).unsqueeze(0).to(device)
    
    # probabilities
    output_probability = model(tensor_question)
    
    # use softmax
    probs = torch.nn.functional.softmax(output_probability, dim=1)
    
    # get max probs
    max_probs, max_indexes = torch.topk(probs,k=words, dim=1)
    
    inverse_vocab = {value:key for key, value in vocab.items()}
    
    response = {
        "Ans" : "",
        "confidence" : []
    }

    for prob, index in zip(max_probs[0], max_indexes[0]):

        response['Ans'] += inverse_vocab[index.item()]
        response['Ans'] += " "
        response['confidence'].append(round(prob.item(), 4))
    
    return response['Ans'], response['confidence']

In [26]:
predict("Jane Armstrong",words=5, threshold=0.5)

('in after that learn which ', [0.4519, 0.186, 0.0598, 0.0501, 0.0363])

In [27]:
df

,question,answer_text
20799,Why did Sue come up to the instructor 's family ?,To have a chat with the couple .
15226,What 's the main idea of the passage ?,An endangered language is spoken by only two p...
12458,What 's the best title for the text ?,Lunches packed with love .
22099,The best title of the passage is,Passing help
27284,What would be the best title for the text ?,An Unusual Architect -- Ieoh Ming Pei
...,...,...
30757,What did Rohm do when she saw the two boys ?,She asked them to ask their parents for help .
11029,We can learn from the passage that,the girl has played ping - pong many times
27722,Hybrid cars consume less energy than conventio...,have electric power to assist when needed
22967,The title of the passage should be,Short stature and short life
